### ISSUE TITLE
In Dark mode, Code editor text color is black

### ISSUE THREAD

**Issue by MartLintz** [Raival-e/File-Explorer#18]
![Screenshot_20220716-172843](https://user-images.githubusercontent.com/107445122/179354531-4128aebf-8f32-4e3f-b7ba-50a8f4e4e04e.png)
![Screenshot_20220716-172856](https://user-images.githubusercontent.com/107445122/179354541-1bf81e76-d4f9-4057-9436-c2162c46e4f2.png)
![Screenshot_20220716-172843](https://user-images.githubusercontent.com/107445122/179354540-b6982ab0-8f95-4569-93c7-1c0aca347e28.png)

**Comment by Raival-e** [comment]
This issue should be solved now, could you check?
