### ISSUE TITLE
APK Download?

### ISSUE THREAD

**Issue by IzzySoft** [Raival-e/File-Explorer#26]
Are there any plans to make the APK of your app available to "the public" (meaning, end-users who cannot compile it themselves and do not use the walled garden of PlayStore)? Would be nice if [releases were tagged](https://github.com/Raival-e/File-Explorer/releases) and the APKs attached to their corresponding releases. Thanks for considering!

**Comment by Raival-e** [comment]
Of course there are, the first release is on the way, I just have a few more things to add/improve. For now, you can use GitHub Actions where a debug build is automatically generated after each push.
Looking forward to your opinion, and thanks for the suggestion!

**Comment by IzzySoft** [comment]
I'd rather wait for the release – that's the place people look first (non-tech-savvy users easily get lost in Github actions). If you could leave a note here in this issue once the first release was tagged and has an APK attached, that would be great. Thanks – and best progress! :crossed_fingers:

**Comment by Raival-e** [comment]
The first [release](https://github.com/Raival-e/File-Explorer/releases/tag/v1.0.0) is out.

**Comment by IzzySoft** [comment]
Thanks @Raival-e – may I ask a few questions on this?

* unfortunately, the APK exceeds the size limit of my repo (which is 30M per app), else the first question would be why not attaching the APK directly instead of putting it into a ZIP file (my updater cannot handle it via ZIPs)
* trying to find out what causes the size of the APK: are those `*.zip` files in e.g. `assets/build` needed in the APK? I found several `src/` structures in different places as well, but here it's especially the `rt.zip` hugely increasing APK size with its 10MB

So if the APK size could be reduced to below 32M, and the APK be attached to releases directly, I could provide your app via my repo. My library scanner didn't report any "offending libs", so from that point it looks very fine.

**Comment by Raival-e** [comment]
Speaking of attaching ZIP file instead of the APK, I've updated the release note and now the attachment is an APK file (I used the zip file generated by GitHub action before, which generates ZIP file that contains the actual app and a metadata file).

As for the size of the app, the main feature of this app is the Java/Kotlin compilers, which unfortunately require that `rt.zip` and `lambda-stubs.zip` (not the "testkey" ones though, these aren't needed anymore, but I forgot to remove them). 
So I'm not really sure if it is possible to shrink the size while having that feature. I'm planning to make a different flavour that doesn't have the compilers, this would bring the size down to ~14MB hopefully. 
I'm a bit busy with studying now, so that would be in my to-do list for the next time.

Thanks again for your interest!

**Comment by IzzySoft** [comment]
> I used the zip file generated by GitHub action before, which generates ZIP file that contains the actual app and a metadata file

Ah, thanks – now I know where that idea comes from :smile:

> As for the size of the app, the main feature of this app is the Java/Kotlin compilers

Ah, then the name "File-Explorer" was a bit misleading – and removing them would rob the app of the main feature users would expect. Let me check the APK again if I can find a third eye to close and make an exception… OK, no offending libs so no Anti-Features needed. And you'll remember to increase `versionCode` with future releases I guess so we don't run into conflicts with that. Hopefully you can find a way to reduce file size in the future (or at least taking care to not having it increase much more).

OK, one [non-critical issue you wish to check](https://www.virustotal.com/gui/file/5be3ff754107a8c9ee373d4c283278ee96ad4916a22e8b9a6e449f82ec9e8db5/detection/f-5be3ff754107a8c9ee373d4c283278ee96ad4916a22e8b9a6e449f82ec9e8db5-1662892991) – my guess is that's something to ignore as that debug key is needed to get a properly signed APK out of the compiler (just telling you anyway so you're aware of it). Apart from that, expect your app to [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.raival.fileexplorer) with the next sync around 6 pm UTC (i.e. in about 7 hours from now) – and be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you like what you see there :smiley:

Before you ask: future updates will be picked up within 24h of your creating a tag and attaching the APK to it. Please keep the current tag naming (i.e. `v<versionName>`) – if you want some test release to not be picked up, simply name the tag something else (e.g. `pre-<versionName>`) or mark it pre-release (which I told my updater to ignore).

**Comment by Raival-e** [comment]
Thanks a lot!

**Comment by Raival-e** [comment]
Hi, I've recently made some changes to the project, the app size has been reduced significantly by removing some unnecessary features that doesn't really fit well in a file explorer app, so I removed the compilers and jar2dex feature. so can you please update app description in IzzyOnDroid website.

**Comment by IzzySoft** [comment]
@Raival-e suggestion: would you accept a PR with the metadata in [Fastlane structures](https://gitlab.com/-/snippets/1895688)? Then I'd send you what is set up here, and you can adjust everything to your liking without the need to wait for me to manually update it locally here. From then on, your metadata updates would be checked (and updated files pulled) whenever a new release is fetched. Deal?

**Comment by Raival-e** [comment]
yeah of course, that would be great.

**Comment by IzzySoft** [comment]
There you go.

As screenshots are already present in your repo, you can simply "move them in". Adjust things as needed, add more locales – just let me know when you've integrated new types as I then need to check to enable them at my end (e.g. if you add a featureGraphic or screenshots, I will then check what is the best way to integrate it; I might automatically convert a PNG to JPEG to safe space/bandwidth, for example, with low-end devices, bad network connections and people with limited data plans in mind).

**Comment by Raival-e** [comment]
Alright, I did modify the description. the screenshots will remain the same.

I have a question, if I changed the description, or maybe added a new locales, would it automatically be updated in your website? or I should let you know to apply the changes?

**Comment by IzzySoft** [comment]
> Alright, I did modify the description.

Looks good, thanks!

> the screenshots will remain the same.

Please take another look at the Cheat Sheet – screenshots are in the wrong place, they need to go one level deeper (into `images/phoneScreenshots/`, not directly into `images/`). Give me a ping when done, so I enable it on my end.

> if I changed the description, or maybe added a new locales, would it automatically be updated in your website?

Yes, when the next release will be pulled. As long as you did not add new "types", it will work directly (e.g. should you add french description, that would work as "description" is already enabled). Just if you add new "types" (e.g. next week you add a featureGraphic) you'd need to drop me a note. And should you need a refresh between releases, I'd need to trigger that manually (as long as it happens occasionally, I'm fine with doing that – but please not twice a week or so :see_no_evil:).

**Comment by Raival-e** [comment]
> screenshots are in the wrong place

alright, now everything in the correct place (hopefully)

> Yes, when the next release will be pulled. As long as you did not add new "types", it will work directly

Great!, thank you 👍

**Comment by IzzySoft** [comment]
Thanks! Screenshots are enabled now as well:

    FastlaneFeatures: shortdesc,fulldescMD,icon,screenshots

(`fulldescMD` means to consider the contents Markdown format; [see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for formatting hints).

**Comment by Raival-e** [comment]
it looks like the information hasn't been updated yet (?)

**Comment by IzzySoft** [comment]
What do you mean? I see the screenshots fine [here](https://apt.izzysoft.de/fdroid/index/apk/com.raival.fileexplorer). Updates will be pulled when there's a new release (last release was before these changes). I've just manually triggered a fastlane update now so everything should be updated today (despite no new release being available).
