### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Github-contribute** [Raival-e/File-Explorer#31]
Finally we have a most advanced file manager app for open source community. I really like the app, Modern UI. Please maintain the project forward. 

Suggestion:
1. Summit to F-Droid
2. Support in build media player (audio & video)
3. Support PDF viewer
4. Edit metadata for audio files, videos and photos.
5. Add checksums in file properties
6. Install bundle app through file-Explorer 
7. Add signing key for apps.

Cons:

1. App is Heavy. Pls reduce app size maximum possible.
2. Pitch to zoom folder and fonts. I feel folder and fonts are small for big phones
3. Search option is not effective. Nothing search maybe be bug.

Today I feel good app is found. Thks for involving the app. Keep going @Raival-e

**Comment by missyraja** [comment]
Ahh yes everyone wants a mixplorer replacement 🤣

**Comment by Github-contribute** [comment]
Mixplorer is still good file manager but problem is not opensource. But this (File-Explorer) app is best replacement for closed source. @missyraja

**Comment by Raival-e** [comment]
Thanks for your suggestions!

> App is Heavy. Pls reduce app size maximum possible.

The File Explorer comes with Kotlin/Java compilers, these two - with their requirements - has increased the app size significantly. I'm planning to make 2 app variants (flavours), one with the compilers, and the other will be without.

> Search option is not effective. Nothing search maybe be bug.

It works as expected for me 🤔. For deep search, there is a size limit for the files that will be scanned, you can adjust it from the settings. I've added that limit to solve #20 .

Thanks again for your suggestions, and they'll be considered.

**Comment by dikasetyaprayogi** [comment]
very awesome app indeed.

we had been longing for pc grade productivity in android file manager and this app tries to make that reality.

suggestion: 

please keep the thumbnail style

i like the thumbnail system keep the thumbnail aspect as the original file, not cropped/squared like many file manager these days. i believe this better as it give full intepretation of the file

*proprietary file manager

![Screenshot_20220916-104118_FX](https://user-images.githubusercontent.com/33314785/190552315-1e67b725-0e04-4131-92b7-c54d50bd8e01.png)

*file explorer

![Screenshot_20220916-104308_File Explorer](https://user-images.githubusercontent.com/33314785/190552431-f7855f2c-7184-4377-8c64-d78f2a229390.png)

also it is also good if long filename can be extended into multiple row like ghost commander

*ghost commander

![Screenshot_20220916-104221_Ghost Commander](https://user-images.githubusercontent.com/33314785/190552712-fecb37d0-09e1-4140-8813-df14c5df02c0.png)

**whis the best for this app**

**Comment by smaragdus** [comment]
@Raival-e 

> The File Explorer comes with Kotlin/Java compilers, these two - with their requirements - has increased the app size significantly. I'm planning to make 2 app variants (flavours), one with the compilers, and the other will be without.

This would be excellent for users like me who do not need these compilers. 1+ for the Lite version! I hope that such a Lite version will be released soon.

**Comment by Raival-e** [comment]
I'll consider all that, Thanks again. I'm a bit busy now, but I'll try my best :)
