### ISSUE TITLE
PDF & checksum calculate

### ISSUE THREAD

**Issue by Baker0o7** [Raival-e/File-Explorer#32]
Please add PDF support and checksum calculate really wonderful app and please always leave it offline 👍👍

**Comment by Baker0o7** [comment]
Add this PDF 
https://github.com/GrapheneOS/PdfViewer

**Comment by nettnikl** [comment]
Hi @Baker0o7 could you kindly create a second issue for the second feature?
e.g. you could remove "checksum calculate" from title and request, and i can create the second issue for you, if you want.

In my experience, it would probably help housekeeping the issues section.

**Comment by Raival-e** [comment]
I'm adding these suggestions to my to-do list.
