### ISSUE TITLE
suggests

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [Raival-e/File-Explorer#34]
Hi i just discover app realy good app and design thanks

1: refresh with pull down same chrome for example
refresh with button i found anoyances 

2: if long press select file or folder because actualy you can actualy only selected all i can,t for example selected 3 files in folder content 6 files

3: add option to select size font in editor
3.1 support editor (html, css, js, jquery,GO......)

4: Support SFTP with PAM suport for sftp with 2FA

thanks you

**Comment by Raival-e** [comment]
> 2: if long press select file or folder because actualy you can actualy only selected all i can,t for example selected 3 files in folder content 6 files

You can select files by clicking on the file icon of the file, though I'm planning to add an option to select files in options menu.

> 3: add option to select size font in editor

The text editor has pinch to zoom feature where you can freely adjust the font size.

And the rest of your suggestions will be considered, Thanks!

**Comment by Disqu3-mirOir-qt** [comment]
tysm for explain i just tested and work perfect
