### ISSUE TITLE
Can't explore root directory. And external storage option is missing from side panel.   Other than that very nice & clean app!

### ISSUE THREAD

**Issue by matt873** [Raival-e/File-Explorer#37]

**Comment by Raival-e** [comment]
Yeah, neither root directory nor external storage (SD card... etc) are supported. 
But I'll try to add those, Thanks for suggestions!

**Comment by domportera** [comment]
external storange and network storage would be great! really love this app's whole concept. seems like it has a ton of potential and I'm really looking forward to using it as it grows

**Comment by Raival-e** [comment]
I'm adding these suggestions to my to-do list.

**Comment by nettnikl** [comment]
Hey, just for reference @Raival-e. This is a absolute must for me, so i started to work on it on a branch.
https://github.com/nettnikl/File-Explorer/tree/add-root-support

**Comment by OkyDooky** [comment]
Not sure if I should open another issue or just leave this here, but adding USB storage to the to-do list would be great. I tried plugging in a mini thumb drive via an A-to-C USB type adapter and this didn't register it, while Simple File Manager did.
Really love this app concept, btw.
