### ISSUE TITLE
Add selection for location when opening new tab

### ISSUE THREAD

**Issue by nettnikl** [Raival-e/File-Explorer#40]
Hey,
first, thanks for this app, looks already very promising! I had trouble finding a good fie explorer since using Android, and at some point started using multiples for different purposes, happy to see a FOSS app that seems to be able to tackle all use cases at once (so happy to see full-featured, not lightweight on the description!), especially multi tab support.

For reference, i found you via the listing in the IzzyOnDroid repos via NeoLauncher.

## What
Regarding these tabs, i would very much welcome to be asked, what to open, whenever i open a new tab.

## How
Opening a little dialogue with the options "internal", "external", "/", supported clouds and local favorite folders could do the trick.
Whatever is not set, not yet granted permission or not yet implemented could be just left out.

On click on one of the options, the corresponding location is opened, without a second click to confirm.
An option could be provided in the settings to always open the same folder, if preferred.

## Why
I use the Download folder, the internal storage root, the external storage root and the device root about the same amount of times and this would speed up my work here greatly.

**Comment by Raival-e** [comment]
Hi, Thanks for your interest, I'm glad that you liked my app.

I'm currently busy with my studies, so there won't be any update until I finish, but your suggestions will surely be considered. I'm planning to make a major changes/improvements to the app. The app size will hopefully be decreased (by removing compiler feature, which contributes to about 60% of the total size).

Regarding accessing folders, you can use bookmarks to navigate to your frequently used folders/files ;)

Thanks!

**Comment by nettnikl** [comment]
Works great thanks!
For reference: implemented in https://github.com/Raival-e/File-Explorer/releases/tag/v1.1.0
