### ISSUE TITLE
Add github issue templates

### ISSUE THREAD

**Issue by nettnikl** [Raival-e/File-Explorer#41]
Hi!
This is a meta request.

Looking at the issues, i see a lot of people flocking to this very promising app. However, i have my doubts that going forward, handling the issues will keep being as manageable as it currently is. I've seen other projects adding templates for github issues, so that people have a guidance how to formulate their feature sugestions (less typing for bug reporters, but easier to manage for you).

Would that help? I might have time at the end of the week to create those, if not done then already (you move quite fast).

**Comment by Raival-e** [comment]
Alright, I've replaced them with better ones, but still, if you have any additional adjustments, feel free to open a pull request.
