### ISSUE TITLE
[Feature]: Add multiple file selection

### ISSUE THREAD

**Issue by HarriBuh** [Raival-e/File-Explorer#61]
### Feature Description

Every file manager I've come across has the feature of selecting multiple files at once. While your app does support the "select all" option (which I rarely use), picking several files at once is a far more common process in file management.

### How can this feature be implemented?

As easy as it is.

### Duplicate feature

- [X] This feature has not been requested yet.

**Comment by Raival-e** [comment]
You can select files by clicking on the icon of the file/folder

**Comment by HarriBuh** [comment]
Oh sorry, I just found out by myself. Nvm then.
