### ISSUE TITLE
[Bug]: File Explorer opens uknown files as *.apk

### ISSUE THREAD

**Issue by PranavPurwar** [Raival-e/File-Explorer#64]
### What happened?

On clicking any uknown file, the explorer tried to open it as if it was an apk file

https://user-images.githubusercontent.com/75154889/225066350-2f040798-3bc2-4c6c-98e9-18d96509df43.mp4

### What's the expected behavior?

It should let the system decide  what actions are possible on that file

### What version of File Explorer you are using?

latest GitHub action

### Duplicate issues

- [X] This issue has not been reported yet.

**Comment by Raival-e** [comment]
If you are using [this build](https://github.com/Raival-e/File-Explorer/actions/runs/4150476931), then it is expected as that build is of the old branch and it is no longer maintained. I would suggest using the [latest release](https://github.com/Raival-e/File-Explorer/releases/tag/v1.1.0) instead.
