### ISSUE TITLE
request: Change `Legacy Tab` to `Material Tab`

### ISSUE THREAD

**Issue by MartLintz** [Raival-e/File-Explorer#9]
![IMG_20220710_143805](https://user-images.githubusercontent.com/107445122/178138747-9b3aead1-0923-46c5-9da4-1cb0500229d3.jpg)
![IMG_20220710_145302](https://user-images.githubusercontent.com/107445122/178138969-b71a2a87-3ee0-436e-b97e-c012d04c5aec.jpg)

**Comment by Raival-e** [comment]
That's a custom made TabView btw, but yeah, It might need some improvements.

**Comment by Raival-e** [comment]
Does it look better now?

**Comment by Raival-e** [comment]
Well, it used to be, but it didn't look as good as it is now. Also, according to Material Guidelines, it's better to have a color fill to provide separation from the content behind it.

Anyway, thanks for your suggestion!

**Comment by Raival-e** [comment]
I intentionally did that, Doesn't look good? It kind of shows the boundaries of each tab.
